name: WorldGuardExtraFlags
version: 0.1
description: '"WorldGuard" extension to add own region flags like white/blacklistes signs or commands or other things. The WorldGuard flags for blocked/allowed commands are not working correctly anyways.'
author: BangL
website: http://bangl.de/
depend: [WorldGuard, WorldEdit, WGCustomFlags]
main: de.bangl.wgef.WorldGuardExtraFlagsPlugin

permissions:
  wgef.regions.own.*:
    default: op
  wgef.regions.own.<region>:
    default: op
  wgef.regions.member.*:
    default: op
  wgef.regions.member.<region>:
    default: op
  wgef.regions.*:
    default: op
  wgef.regions.<region>:
    default: op
  wgef.flags.signs-block.*:
    default: op
  wgef.flags.signs-allow.*:
    default: op
  wgef.flags.cmds-block.*:
    default: op
  wgef.flags.cmds-allow.*:
    default: op
  wgef.flags.enderchest-access.*:
    default: op
  wgef.flags.enderpearl.*:
    default: op
  wgef.flags.leaf-growth.*:
    default: op
  wgef.flags.*:
    default: op