name: WGSignFlags
version: 0.1
description: '"WorldGuard" extension to add own region flags to allow or block signs.'
authors: [BangL, mewin]
website: http://bangl.de/
depend: [WorldGuard, WGCustomFlags]
main: de.bangl.wgsf.WGSignFlagsPlugin
