name: WGSignFlags
main: de.bangl.wgsf.WGSignFlagsPlugin
description: WorldGuard extension to block the creation of signs in specific regions.
version: 0.1

authors: [ BangL, mewin ]
depend: [ WorldGuard, WGCustomFlags ]
softdepend: [ WorldEdit ]
